#!/usr/bin/env python3
"""
Critical mirror outage alert manager for china-mirror-skills.

Creates or updates a single GitHub issue when one or more categories have
no working mirrors left, and closes the alert issue after recovery.
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

import requests

ISSUE_TITLE = "[Mirror Alert] Critical mirror outage"
ISSUE_LABELS = ["mirror-alert", "automated"]


def load_report(report_path: Path) -> dict | None:
    """Load the generated mirror health report."""
    if not report_path.exists():
        return None
    with open(report_path, "r", encoding="utf-8") as f:
        return json.load(f)


def critical_categories(report: dict | None) -> list[str]:
    """Return categories with zero working mirrors."""
    if not report:
        return []
    return list(report.get("summary", {}).get("critical_categories", []))


def github_headers(token: str) -> dict[str, str]:
    """Return standard GitHub API headers."""
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def list_open_alert_issues(repo: str, token: str) -> list[dict]:
    """List open mirror alert issues."""
    url = f"https://api.github.com/repos/{repo}/issues"
    response = requests.get(
        url,
        params={
            "state": "open",
            "labels": ",".join(ISSUE_LABELS),
            "per_page": 100,
        },
        headers=github_headers(token),
        timeout=30,
    )
    response.raise_for_status()
    return response.json()


def patch_issue(repo: str, token: str, issue_number: int, payload: dict):
    """Update an issue."""
    url = f"https://api.github.com/repos/{repo}/issues/{issue_number}"
    response = requests.patch(
        url,
        json=payload,
        headers=github_headers(token),
        timeout=30,
    )
    response.raise_for_status()
    return response.json()


def create_issue(repo: str, token: str, payload: dict):
    """Create a new issue."""
    url = f"https://api.github.com/repos/{repo}/issues"
    response = requests.post(
        url,
        json=payload,
        headers=github_headers(token),
        timeout=30,
    )
    response.raise_for_status()
    return response.json()


def build_issue_body(report: dict, categories: list[str]) -> str:
    """Build the critical outage issue body."""
    metadata = report.get("metadata", {})
    rankings = report.get("category_rankings", {})

    lines = [
        "## Critical Mirror Outage",
        "",
        "One or more mirror categories have no working mirror in the latest daily health check.",
        "",
        f"- Report generated at: `{metadata.get('generated_at', 'unknown')}`",
        f"- Critical categories: `{', '.join(categories)}`",
        "",
        "### Impacted Categories",
        "",
    ]

    for category in categories:
        ranking = rankings.get(category, {})
        lines.append(f"#### `{category}`")
        lines.append("")
        for result in ranking.get("ranked_results", []):
            response_time = result.get("response_time_ms")
            latency = f" ({response_time}ms)" if response_time is not None else ""
            lines.append(
                f"- `{result['status']}` {result['name']} -> {result['url']}{latency}"
            )
        lines.append("")

    lines += [
        "### Action Items",
        "",
        "- [ ] Verify whether the outage is temporary or persistent",
        "- [ ] Update `data/mirrors.yml` if a mirror has been deprecated or changed policy",
        "- [ ] Regenerate README after the mirror set is corrected",
        "",
        "---",
        f"_Updated at: {datetime.utcnow().isoformat()}Z_",
        "_Generated by mirror-health workflow_",
    ]

    return "\n".join(lines)


def main():
    script_dir = Path(__file__).parent.absolute()
    project_root = script_dir.parent
    report_path = project_root / "reports" / "report.json"

    report = load_report(report_path)
    categories = critical_categories(report)

    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")

    if not token or not repo:
        if categories:
            print(f"Would open/update alert issue for: {', '.join(categories)}")
        else:
            print("No critical categories and no GitHub credentials; nothing to sync")
        return

    try:
        open_issues = list_open_alert_issues(repo, token)
        if categories:
            payload = {
                "title": ISSUE_TITLE,
                "body": build_issue_body(report, categories),
                "labels": ISSUE_LABELS,
            }
            if open_issues:
                primary = open_issues[0]
                patch_issue(repo, token, primary["number"], payload)
                print(f"Updated alert issue #{primary['number']}")
                for duplicate in open_issues[1:]:
                    patch_issue(
                        repo,
                        token,
                        duplicate["number"],
                        {"state": "closed"},
                    )
                    print(f"Closed duplicate alert issue #{duplicate['number']}")
            else:
                issue = create_issue(repo, token, payload)
                print(f"Created alert issue #{issue['number']}")
        else:
            for issue in open_issues:
                patch_issue(
                    repo,
                    token,
                    issue["number"],
                    {
                        "state": "closed",
                        "body": (
                            issue.get("body", "")
                            + "\n\n---\n_Closed automatically after all categories recovered._"
                        ),
                    },
                )
                print(f"Closed recovered alert issue #{issue['number']}")
            if not open_issues:
                print("No critical categories; no alert issue to close")
    except requests.RequestException as exc:
        print(f"Failed to sync mirror alert issue: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
