#!/usr/bin/env python3
"""
Weekly curation script for china-mirror-skills

Reads the latest mirror health report and creates a weekly GitHub issue
with a checklist summarizing failed/degraded mirrors for human review.
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

import requests


def load_report(report_path: Path) -> dict | None:
    """Load mirror health report from JSON file."""
    if report_path.exists():
        with open(report_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return None


def create_github_issue(title: str, body: str):
    """Create a GitHub issue via the API."""
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")

    if not token or not repo:
        print("Warning: GITHUB_TOKEN or GITHUB_REPOSITORY not set, skipping issue creation")
        print(f"Would have created issue: {title}")
        print(body)
        return

    url = f"https://api.github.com/repos/{repo}/issues"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload = {
        "title": title,
        "body": body,
        "labels": ["weekly-curation", "automated"],
    }

    response = requests.post(url, json=payload, headers=headers, timeout=30)
    if response.status_code == 201:
        issue_url = response.json().get("html_url", "")
        print(f"Created issue: {issue_url}")
    else:
        print(f"Failed to create issue: {response.status_code} {response.text}", file=sys.stderr)
        sys.exit(1)


def build_issue_body(report: dict | None, week_str: str) -> str:
    """Build the issue body from the health report."""
    lines = [
        f"## Weekly Mirror Curation - {week_str}",
        "",
        "_This issue is auto-generated weekly. Review failed/degraded mirrors and take action._",
        "",
    ]

    if report is None:
        lines += [
            "### No Health Report Available",
            "",
            "No `reports/report.json` was found. The mirror-health workflow may not have run yet.",
            "",
            "**Action items:**",
            "- [ ] Manually trigger the `mirror-health` workflow",
            "- [ ] Verify that `scripts/check_mirrors.py` runs without errors",
            "",
        ]
        lines += [
            "---",
            f"_Generated at: {datetime.utcnow().isoformat()}Z_",
            "_Generated by weekly-curation workflow_",
        ]
        return "\n".join(lines)

    metadata = report.get("metadata", {})
    summary = report.get("summary", {})
    results = report.get("results", [])
    recommendations = report.get("recommendations", [])

    total = summary.get("total_mirrors", 0)
    healthy = summary.get("healthy", 0)
    unhealthy = summary.get("unhealthy", 0)
    health_rate = summary.get("health_rate", 0)
    generated_at = metadata.get("generated_at", "unknown")

    lines += [
        "### Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Report generated | {generated_at} |",
        f"| Total mirrors | {total} |",
        f"| Healthy | {healthy} ({health_rate}%) |",
        f"| Unhealthy | {unhealthy} |",
        "",
    ]

    # Failed mirrors
    failed = [r for r in results if r["status"] != "ok"]
    if failed:
        lines += [
            "### Failed / Degraded Mirrors",
            "",
            "Please investigate the following mirrors:",
            "",
        ]
        for r in failed:
            status_label = r["status"].replace("_", " ").title()
            error = r.get("error_message", "")
            error_str = f" — {error}" if error else ""
            lines.append(f"- [ ] **{r['name']}** (`{r['category']}`) — {status_label}{error_str}")
            lines.append(f"  - URL: {r['url']}")
        lines.append("")
    else:
        lines += [
            "### Failed / Degraded Mirrors",
            "",
            "✅ All mirrors are healthy this week!",
            "",
        ]

    # Recommendations
    if recommendations:
        lines += [
            "### Recommendations",
            "",
        ]
        for rec in recommendations:
            icon = "🔴" if rec["severity"] == "critical" else "🟡"
            lines.append(f"- {icon} **[{rec['category']}]** {rec['message']}")
            lines.append(f"  - Action: {rec['action']}")
        lines.append("")

    # Category health
    cat_stats = summary.get("category_stats", {})
    if cat_stats:
        lines += [
            "### Category Health",
            "",
            "| Category | Healthy | Total | Status |",
            "|----------|---------|-------|--------|",
        ]
        for cat, stats in sorted(cat_stats.items()):
            icon = "✅" if stats["failed"] == 0 else "⚠️"
            lines.append(f"| {cat} | {stats['ok']} | {stats['total']} | {icon} |")
        lines.append("")

    # Action items
    lines += [
        "### Action Items",
        "",
        "- [ ] Review all failed mirrors above",
        "- [ ] Update `data/mirrors.yml` if any mirrors are permanently down",
        "- [ ] Check for new mirrors to add (TUNA/USTC announcements)",
        "- [ ] Close this issue when all items are resolved",
        "",
        "---",
        f"_Generated at: {datetime.utcnow().isoformat()}Z_",
        "_Generated by weekly-curation workflow_",
    ]

    return "\n".join(lines)


def main():
    script_dir = Path(__file__).parent.absolute()
    project_root = script_dir.parent
    report_path = project_root / "reports" / "report.json"

    print("China Mirror Skills - Weekly Curation")
    print("=" * 40)

    report = load_report(report_path)
    if report:
        print(f"Loaded report from: {report_path}")
        generated_at = report.get("metadata", {}).get("generated_at", "unknown")
        print(f"Report generated at: {generated_at}")
    else:
        print("No health report found, will create issue noting this")

    week_str = datetime.utcnow().strftime("Week of %Y-%m-%d")
    title = f"[Weekly Curation] Mirror Health Review — {week_str}"
    body = build_issue_body(report, week_str)

    print(f"\nCreating GitHub issue: {title}")
    create_github_issue(title, body)
    print("\nDone.")


if __name__ == "__main__":
    main()
